config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :project_groups
  resources :customers
  get 'tasks/next', 'tasks#next'
  post 'tasks/comment', 'tasks#comment'
  root to: 'home#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :projects

  before_save :replace_with_existing, if: ->(customer) { customer.projects.empty? }

  def replace_with_existing
    customer = Customer.find_by_name name
    return false if customer && name
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates_presence_of :name, :project_group
  belongs_to :customer
  belongs_to :project_group
  before_save :set_default_dates

  def set_default_dates
    self.start_date = DateTime.now unless start_date
    self.end_date = DateTime.now unless end_date
  end

  def task_names
    names = []
    project_group.tasks.each do |task|
      names.push task.name
    end
    names
  end

  def tasks_in_order!
    map = {}
    tasks!.each do |t|
      map.merge! t.task.name => t
    end
    list = []
    task_names.each do |t|
      list << map[t.to_s] unless map[t.to_s].nil?
    end
    list
  end

  def tasks!
    return tasks unless tasks.empty?
    tasks = []
    task_names.each do |t|
      project_group_task = project_group.tasks.find_by_name t
      tasks << Task.new(name: t.to_s, task: project_group_task)
    end
    self.tasks = tasks
    save!
    self.tasks
  end

  def all_ready?
    tasks!.each do |t|
      return false unless t.ready?
    end
    true
  end

  def customer!
    return customer if customer
    self.customer = Customer.new unless customer
    customer.save!
    save!
    customer
  end

  def start_end_date
    "#{start_date}-#{end_date}"
  end
end

app/models/project_group.rb
class ProjectGroup < ActiveRecord::Base
  has_many :projects
  has_many :tasks, -> { order(:id) }, inverse_of: :project_group
  accepts_nested_attributes_for :tasks

  def new_project
    project = Project.new
    project.project_group = self
    project.build_customer
    project
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :task
  validates_presence_of :task, :code

  def number_of_phases
    3
  end

  def next
    self.code = code + 1
    self.code = 0 if code > number_of_phases - 1
  end

  def css_classes
    %w(nop do done)
  end

  def css_class
    css_classes[code]
  end

  def ready?
    code + 1 == number_of_phases
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :name
  belongs_to :project, optional: true
  has_one :status
  has_many :tasks
  belongs_to :task, optional: true
  belongs_to :project_group, inverse_of: :tasks, optional: true
  default_scope -> { order(:id) }

  def status!
    self.status = Status.create! task: self if status.nil?
    status
  end

  def ready?
    status!.ready?
  end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def name
    old_customer = Customer.find_by_name params[:value]
    customer = Customer.find params[:id]
    if old_customer && old_customer.id != customer.id
      old_customer.projects << customer.projects
      old_customer.save!
      customer.destroy
    else
      customer.name = params[:value]
      customer.save!
    end
    render text: params[:value]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render text: '', layout: true
  end
end

app/controllers/project_groups_controller.rb
class ProjectGroupsController < ApplicationController
  def new
    @project_group = ProjectGroup.new
    id = params['id'] || params['tasks']
    id.to_i.times { @project_group.tasks.build }
  end

  def edit
    @project_group = ProjectGroup.find params[:id]
  end

  def index
    @project_groups = ProjectGroup.all
  end

  def create
    @project_group = ProjectGroup.new project_group_params
    pp @project_group.valid?
    pp @project_group.errors.full_messages
    @project_group.save ? redirect_to(project_groups_path) : render(action: :new)
  end

  def update
    project_group = ProjectGroup.find params[:id]
    project_group.update_attributes params[:project_group]
    redirect_to project_groups_path
  end

  def destroy
    project_group = ProjectGroup.find params[:id]
    project_group.projects.each do |project|
      project.tasks.each do |task|
        task.status.destroy if task.status
        task.destroy
      end
      project.customer.destroy if project.customer
      project.destroy
    end
    project_group.tasks.each(&:destroy)
    project_group.destroy
    redirect_to project_groups_path
  end

  private

  def project_group_params
    params.require(:project_group).permit(:name, tasks_attributes: [:id, :name])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @project_group = ProjectGroup.find params['group-id']
    ProjectRemover.new.remove_all_ready(@project_group) unless params[:all] == '1' 
    @selected_id = params[:selected]
  end

  def create
    project = Project.new project_params
    project.customer = Customer.new
    group_id = params[:project][:project_group_id]
    project.project_group = ProjectGroup.find group_id
    project.save!
    redirect_to projects_path('group-id' => group_id)
  end

  private

  def name
    update_attribute 'name', params
  end

  def description
    update_attribute 'description', params
  end

  def state
    update_attribute 'state', params
  end

  def update_attribute(attribute, params)
    project = Project.find params[:id]
    value = params[:value]
    project.send attribute + '=', value
    project.save!
    render text: (project.send attribute)
  end

  def update_time_attribute(attribute, params)
    params[:value] =~ / *([^ ]+) */
    params[:value] = Regexp.last_match(1)
    update_attribute attribute, params
  end

  def start_date
    update_time_attribute 'start_date', params
  end

  def end_date
    update_time_attribute 'end_date', params
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def next
    task = Task.find params[:id]
    task.status.next
    task.status.save
    if task.project.all_ready?
      render text: '!ready'
    else
      render text: task.status.css_class
    end
  end

  def comment
    task = Task.find params[:id]
    comment = params[:value]
    task.status.comment = comment
    task.status.save!
    render text: params[:value]
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_groups_helper.rb
module ProjectGroupsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
%html
  %head
    = stylesheet_link_tag :application
    = javascript_include_tag :application
  %body
    #navcontainer
      %ul#nav-bar
        %li
          = link_to "Projektiryhmät", project_groups_path
        %li
          = link_to "Uusi projektiryhma", new_project_group_path({:tasks => 5})
    #container
      = yield

app/views/project_groups/_form.html.haml
= f.label :name
= f.text_field :name

.task
  %h2 Työvaiheiden nimet
  = f.fields_for :tasks do |t|
    =# t.error_messages
    = t.text_field :name

= submit_tag

app/views/project_groups/edit.html.haml
= form_for @project_group do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/project_groups/index.html.haml
%ul#project-groups
  - @project_groups.each do |pg|
    %li.project-group
      %span.project-group
        = link_to pg.name, projects_path(:'group-id' => pg.id)
      %span.modify
        = link_to "Muokkaa", edit_project_group_path(pg)
        = link_to "Poista", project_group_path(pg), :confirm => 'Oletko varma', :method => :delete

app/views/project_groups/new.html.haml
= form_for @project_group do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/projects/index.html.haml
- if request.parameters[:all] == "1"
  = link_to "Piilota valmiit", request.parameters.merge({:all => 0})
- else
  = link_to "Näytä valmiit", request.parameters.merge({:all => 1})
%h2= h @project_group.name
- if @project_group.projects.size > 0
  %div
    %table#projects{ 'data-tasks' => @project_group.tasks.size }
      %thead
        %tr
          %th Projektin nimi
          -@project_group.projects.first.task_names.each do |t|
            %th= h t.to_s
      %tfoot
        %tr
          %th Projektin nimi
          -@project_group.projects.first.task_names.each do |t|
            %th= h t.to_s
      %tbody
        -@project_group.projects.each do |p|
          %tr{:class => p.id.to_s != @selected_id && "oneline"}
            - if p.id.to_s != @selected_id
              %td.input{"data-id" => p.id, "data-url" => "/projects/name"}
                = link_to h(p.name), request.parameters.merge({ :selected => p.id })
            - else
              %td.input{"data-id" => p.id, "data-url" => "/projects/name"}= h(p.name)
            - p.tasks_in_order!.each do |t|
              %td{:class => "task #{t.status!.css_class}", "data-code" => t.status!.code, "data-id" => t.id} 
                %span.comment{"data-id" => t.id, "data-code" => t.status!.code}= h "#{t.status!.comment}"
                -if @selected_id == p.id.to_s
                  %span.colorChanger{"data-id" => t.id} &gt;
%div
  %h4 Uusi projekti
  = form_for @project_group.new_project do |f|
    = f.hidden_field :project_group_id
    %table#new-project
      %thead
        %tr
          %th Uuden projektin nimi
          %th OK
        %tr
          %td= f.text_field :name
          %td
            %button( type="submit" ) Lisää